name: Build Image and workspace

on:
  push:
    branches: [ dev-ci ]
  pull_request:
    branches: [ dev-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3

    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: ./build.sh